### ISSUE TITLE
add support for events at the root level of the collection

### ISSUE THREAD

**Issue by chrisnesbit1** [rbretecher/go-postman-collection#11]
I would like to contribute a PR for adding events at the root level of the collection. 

This would add the event to the "Prequest Script" and/or "Tests" tabs in the Collection's settings screen in PostMan. These are the scripts that would be run for all `Item` in that collection.

**Comment by rbretecher** [comment]
Closing this issue as events support has been added since [v0.7.0](https://github.com/rbretecher/go-postman-collection/releases/tag/v0.7.0).
