### ISSUE TITLE
Support Description Objects

### ISSUE THREAD

**Issue by grokify** [rbretecher/go-postman-collection#14]
The Postman Collection spec describes the `description` object as being an object or a string.

> A Description can be a raw text, or be an object, which holds the description along with its format.

https://schema.postman.com/collection/json/v2.1.0/draft-04/collection.json

Currently, only string is supported.

The goal is to support the description object which enables setting a MIME `type` (either `text/markdown` or `text/plain`) and `version`.

```json
{
  "description":{
    "$schema":"http://json-schema.org/draft-04/schema#",
    "id":"#/definitions/description",
    "description":"A Description can be a raw text, or be an object, which holds the description along with its format.",
    "oneOf":[
      {
        "type":"object",
        "title":"Description",
        "properties":{
          "content":{
            "type":"string",
            "description":"The content of the description goes here, as a raw string."
          },
          "type":{
            "type":"string",
            "description":"Holds the mime type of the raw description content. E.g: 'text/markdown' or 'text/html'.\nThe type is used to correctly render the description when generating documentation, or in the Postman app."
          },
          "version":{
            "description":"Description can have versions associated with it, which should be put in this property."
          }
        }
      },
      {
        "type":"string"
      },
      {
        "type":"null"
      }
    ]
  }
}
```

**Comment by rbretecher** [comment]
Hello,

Thanks for the issue. I just made a new release [v0.5.0](https://github.com/rbretecher/go-postman-collection/releases/tag/v0.5.0) that adds support for description as an object.

I'm closing this issue as it should be solved but feel free to reopen it if needed.

**Comment by rbretecher** [comment]
Hello,

Thanks for the issue. I just made a new release [v0.5.0](https://github.com/rbretecher/go-postman-collection/releases/tag/v0.5.0) that adds support for description as an object.

I'm closing this issue as it should be solved but feel free to reopen it if needed.
