### ISSUE TITLE
Q: Does this library support to make API call thru Golang instead of Postman?

### ISSUE THREAD

**Issue by kishorevaishnav** [rbretecher/go-postman-collection#19]
Are you planning to read the collection and do the API requests thru Golang - so that collection json file is been reused if we want to ignore the postman binary for any projects.

In other words, during development would like to use Postman for testing & debugging, but then would like to re-use the collection json file to be embedded with golang and make API calls thru this library.

**Comment by rbretecher** [comment]
Hello :)

I'm not sure to understand what you're trying to achieve but this library has been built it order to create collections, manipulate them and then export them in a format that the Postman Apps can consume.

This library is not intended to be a client to help you call your API.

Closing this issue for now but feel free to reopen it if you think that it does not answer your question :)

**Comment by kishorevaishnav** [comment]
thx.
