### ISSUE TITLE
Converting to HTTP requests

### ISSUE THREAD

**Issue by vbisbest** [rbretecher/go-postman-collection#3]
I am curious if there is a method or example of reading a postman collection and turning all of the calls into HTTP requests.  This would include auth and variables as well.  Or is this something that we need to piece together manually?  Thank you!

**Comment by rbretecher** [comment]
What do you exactly mean by "turning all of the calls into HTTP requests" ? Could you give me an example ?

**Comment by rbretecher** [comment]
I'm closing this issue as OP didn't answer.

Feel free to reopen it if needed :)
