### ISSUE TITLE
Missing Auth node

### ISSUE THREAD

**Issue by vbisbest** [rbretecher/go-postman-collection#4]
The library seems to be missing the root postman collection auth node.  It should be at the same level as :
Info
Items
Variables
Auth (Missing)

**Comment by rbretecher** [comment]
There is an open PR to add the `Auth` node in the `Collection` struct : https://github.com/rbretecher/go-postman-collection/pull/8

**Comment by rbretecher** [comment]
Closing this issue as the Auth field has been added in [release v0.4.0](https://github.com/rbretecher/go-postman-collection/releases/tag/v0.4.0).
